# -*- coding: utf-8 -*-
"""conversao.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lThmqv7t_Uo986Pmf3BXj08esMY0lAqR
"""

nome1 = input('Nome do Corredor 1:\t')
nome2 = input('Nome do Corredor 2:\t')

milha1 = float(input(f'Milha percorida pelo corredor 1:\t'))
milha2 = float(input(f'Milha percorrida pelo corredor 2:\t'))


conversão1 = (milha1 + (0,6))
conversão2 = (milha2 + (0,6))

print(nome1, 'fez', conversão1,'KM{:.1%}'.format(conversão))
print( nome2, 'fez', conversão2, 'KM{:.1%}'.format(conersão))